import requests
import json

# This url requests the creation of a linked service by providing the name of said service along with the devlopment endpoint of the wokspace
url = "https://ri11ushi.dev.azuresynapse.net//linkedservices/RestConnectorService?api-version=2020-12-01"

# Payload defines all the properties required to create a functional linked service
payload = json.dumps({
  "properties": {
    "type": "RestService",
    "typeProperties": {
      # Base URL that leverages Search API to fetch data from OAK instance
      "url": "https://testvik4.oep.ppe.azure-int.net/api/search/v2/query",
      "enableServerCertificateValidation": 'true',
      "authenticationType": "Anonymous",
    "authHeaders": {
                "Data-Partition-Id": {
                    "type": "SecureString",
                    "value": "testvik4-part-1"
                },
                "Authorization": {
                    "type": "SecureString",
                    # This token is generated by the Login API of OSDU services
                    "value": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiIyZjU5YWJiYy03YjQwLTRkMGUtOTFiMi0yMmNhMzA4NGJjODQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwiaWF0IjoxNjU2MDY2NTMyLCJuYmYiOjE2NTYwNjY1MzIsImV4cCI6MTY1NjE1MzIzMiwiYWlvIjoiRTJaZ1lKQlp4TFpkNTVnUXo2MnovWHJmbHRmekFnQT0iLCJhcHBpZCI6IjJmNTlhYmJjLTdiNDAtNGQwZS05MWIyLTIyY2EzMDg0YmM4NCIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0Ny8iLCJvaWQiOiI1MWQyZjc5MS03OTViLTRjOGQtOTY1Ny1jZDIzYjFmOWYyYTciLCJyaCI6IjAuQVJvQXY0ajVjdkdHcjBHUnF5MTgwQkhiUjd5cldTOUFldzVOa2JJaXlqQ0V2SVFhQUFBLiIsInN1YiI6IjUxZDJmNzkxLTc5NWItNGM4ZC05NjU3LWNkMjNiMWY5ZjJhNyIsInRpZCI6IjcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0NyIsInV0aSI6InhoNUhISlpiM0UyZmRBUi1COGNTQUEiLCJ2ZXIiOiIxLjAifQ.NTnrh0k5VobKuwAScxHhfmKYIWMihUY4LhrxY0VIQOjAx_qlUjaV5nzk7hmdTqStSu-Ab1t9RlbCOklYZ4Z2SpSHkBse52sqr_FCK6Gl8lyD-7R5oSUXfKFjvkprH1VHAXHQbfFHWOldzMIZe1XWk4d83bdzS9gHnm5MC6aHdEA4osnmgn3_NOKjkOCUcTBgSahUAEsmG2qxR-pKpS-BeJm5kKMvOoDzC8edERjyaaZ4oUfYKqIFpKBxphp1yPztYOADYwRvtpsu10EMWr_PU0FJw-4xfLcMqFjcU4SRGEaWwhHxydmeGcIAdJGpxEajqm_605j0haSIaB6MPTuLCQ"
                }
            },
      "connectionString": {
        "type": "SecureString",
        "value": "DefaultEndpointsProtocol=https;AccountName=ritushitestpost;AccountKey=<storage key>"
      }
    }
  }
})
headers = {
  'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiJodHRwczovL2Rldi5henVyZXN5bmFwc2UubmV0IiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3LyIsImlhdCI6MTY1NjA1NTU3NywibmJmIjoxNjU2MDU1NTc3LCJleHAiOjE2NTYwNjA3NzMsIl9jbGFpbV9uYW1lcyI6eyJncm91cHMiOiJzcmMxIn0sIl9jbGFpbV9zb3VyY2VzIjp7InNyYzEiOnsiZW5kcG9pbnQiOiJodHRwczovL2dyYXBoLndpbmRvd3MubmV0LzcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0Ny91c2Vycy83NWQ5YmU1Mi1lNTg0LTRkNTUtODI4NS1hODZlYWIzNmFlYjAvZ2V0TWVtYmVyT2JqZWN0cyJ9fSwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhUQUFBQThvZk9RNnZLc0JGNWxkanpMZjA2aitkbVpnTGcrbUVmREtITzBUSWdEc0lxVlBHNkd0TzY2VWdMTVlyODRUT3EwNUluaHBJWE1xaUV6WWxURG5Nc3ZrMGdQVHB4UzBlOHZHK3NaNnkvRTVJPSIsImFtciI6WyJwd2QiLCJyc2EiLCJ3aWEiLCJtZmEiXSwiYXBwaWQiOiJiNjc3YzI5MC1jZjRiLTRhOGUtYTYwZS05MWJhNjUwYTRhYmUiLCJhcHBpZGFjciI6IjAiLCJkZXZpY2VpZCI6ImU1ODliMGNiLWIyMjEtNDRmZi1hMWQ4LWM5YzlmZDEyNGE3MSIsImZhbWlseV9uYW1lIjoiU2hhbmtlciIsImdpdmVuX25hbWUiOiJSaXR1c2hpIiwiaW5fY29ycCI6InRydWUiLCJpcGFkZHIiOiIyMC41Ni4xOTMuMTczIiwibmFtZSI6IlJpdHVzaGkgU2hhbmtlciIsIm9pZCI6Ijc1ZDliZTUyLWU1ODQtNGQ1NS04Mjg1LWE4NmVhYjM2YWViMCIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0yMTI3NTIxMTg0LTE2MDQwMTI5MjAtMTg4NzkyNzUyNy01NzUyNTMzNiIsInB1aWQiOiIxMDAzMjAwMUY5ODczMDRBIiwicmgiOiIwLkFSb0F2NGo1Y3ZHR3IwR1JxeTE4MEJIYlIzNWN3QnJTRWdWR3Y1MVVuWEJCeHJNYUFDay4iLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJzdWIiOiJjU3lPelJ5Z29sMGp5b1ZtZHJXR1dreUgxc05uSkV5ZmFMc3dnT0tDcFlBIiwidGlkIjoiNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3IiwidW5pcXVlX25hbWUiOiJ0LXJzaGFua2VyQG1pY3Jvc29mdC5jb20iLCJ1cG4iOiJ0LXJzaGFua2VyQG1pY3Jvc29mdC5jb20iLCJ1dGkiOiJFN1VzeGRBU2FVcTIxV3VUeDhJSUFBIiwidmVyIjoiMS4wIn0.jyQHBznLysfJriqVS6m956m9t3Se0ioAOkL-3FA7qeVGep5PdfA7fwqB1HLfAxHnL26pxy2mr0lVipfucdbOkqreacEW2s2BpfjpgxeklkS5oIEjQlE9RjtqADJ5K4oQLg8Wm7_wkwmCYrpE7Po1_bba95DBf95GSlChFkXolUKc6mKt0NzDwn0VdVIozkoSW727-19WxCEmWNCOWwryVUeiNMHPs4MxGPHW39YTDHpQgiV9o4emAeluYM5oNHELfb4kLAQMN2YHvSoJJyc7B5SnnU750skTA-5aLWTkNYEVeRaWy1KTOuj1TpoeX4i4-DZ3Ybo6OlJg1QnBH7RkQQ',
  'Content-Type': 'application/json'
}

response = requests.request("PUT", url, headers=headers, data=payload)

print(response.text)
